insert into public.movies (
  id,
  title,
  description,
  poster_url,
  backdrop_url,
  video_url,
  video_type,
  genres,
  release_year,
  rating,
  duration_minutes,
  is_featured,
  source_name,
  license_note
) values
(
  '11111111-1111-4111-8111-111111111111',
  'Night of the Living Dead',
  'George A. Romero''s landmark independent horror film, available from Internet Archive with a public-domain mark.',
  'https://archive.org/services/img/NightOfTheLivingDead_201508',
  'https://archive.org/services/img/NightOfTheLivingDead_201508',
  'https://archive.org/download/NightOfTheLivingDead_201508/Night%20of%20the%20Living%20Dead.mp4',
  'mp4',
  array['Horror', 'Classic', 'Public Domain'],
  1968,
  'NR',
  95,
  true,
  'Internet Archive',
  'Public Domain Mark 1.0 on the Internet Archive item.'
),
(
  '22222222-2222-4222-8222-222222222222',
  'His Girl Friday',
  'A fast-talking screwball comedy starring Cary Grant and Rosalind Russell, sourced from a public-domain-marked Internet Archive item.',
  'https://archive.org/services/img/his-girl-friday-1940_202310',
  'https://archive.org/services/img/his-girl-friday-1940_202310',
  'https://archive.org/download/his-girl-friday-1940_202310/His%20Girl%20Friday%20%281940%29.mp4',
  'mp4',
  array['Comedy', 'Romance', 'Public Domain'],
  1940,
  'NR',
  92,
  true,
  'Internet Archive',
  'Public Domain Mark 1.0 on the Internet Archive item.'
),
(
  '33333333-3333-4333-8333-333333333333',
  'The General',
  'Buster Keaton''s silent action-comedy classic, presented here from a public-domain-marked Internet Archive source.',
  'https://archive.org/services/img/TheGeneral1926',
  'https://archive.org/services/img/TheGeneral1926',
  'https://archive.org/download/TheGeneral1926/The_General_1926_720p_512kb.mp4',
  'mp4',
  array['Silent Film', 'Comedy', 'Public Domain'],
  1926,
  'NR',
  75,
  false,
  'Internet Archive',
  'Public Domain Mark 1.0 on the Internet Archive item.'
),
(
  '44444444-4444-4444-8444-444444444444',
  'The Stranger',
  'Orson Welles directs and stars in this tense post-war thriller, available from Internet Archive under a public-domain license note.',
  'https://archive.org/services/img/TheStranger_0',
  'https://archive.org/services/img/TheStranger_0',
  'https://archive.org/download/TheStranger_0/The_Stranger_512kb.mp4',
  'mp4',
  array['Thriller', 'Noir', 'Public Domain'],
  1946,
  'NR',
  95,
  false,
  'Internet Archive',
  'Public domain license note on the Internet Archive item.'
),
(
  '55555555-5555-4555-8555-555555555555',
  'Nosferatu',
  'A restored shareable version of the silent vampire classic, sourced from a Creative Commons Internet Archive item.',
  'https://archive.org/services/img/ToddKelsoAKAnihilator77_3',
  'https://archive.org/services/img/ToddKelsoAKAnihilator77_3',
  'https://archive.org/download/ToddKelsoAKAnihilator77_3/Nosferatu1.0_512kb.mp4',
  'mp4',
  array['Horror', 'Silent Film', 'Creative Commons'],
  1922,
  'NR',
  94,
  false,
  'Internet Archive',
  'Creative Commons Attribution-NonCommercial-ShareAlike 2.5 on the Internet Archive item.'
),
(
  '66666666-6666-4666-8666-666666666666',
  'Big Buck Bunny',
  'The Blender Foundation open movie short, included as a lightweight legal playback test with a Creative Commons license.',
  'https://archive.org/services/img/BigBuckBunny_328',
  'https://archive.org/services/img/BigBuckBunny_328',
  'https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4',
  'mp4',
  array['Animation', 'Family', 'Creative Commons'],
  2008,
  'All',
  10,
  false,
  'Internet Archive',
  'Creative Commons Attribution 3.0 United States on the Internet Archive item.'
)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  poster_url = excluded.poster_url,
  backdrop_url = excluded.backdrop_url,
  video_url = excluded.video_url,
  video_type = excluded.video_type,
  genres = excluded.genres,
  release_year = excluded.release_year,
  rating = excluded.rating,
  duration_minutes = excluded.duration_minutes,
  is_featured = excluded.is_featured,
  source_name = excluded.source_name,
  license_note = excluded.license_note;
